require: rubocop-performance
inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml

Security/Open:
  Exclude:
    - "core/lib/bfs/bucket/abstract.rb"
    - "core/lib/bfs/blob.rb"
