inherit_from:
  - https://storage.googleapis.com/bsm-misc/rubocop.yml

AllCops:
  Exclude:
    - "vendor/**/*"

Security/Open:
  Exclude:
    - "core/lib/bfs/bucket/abstract.rb"
Metrics/BlockLength:
  Exclude:
    - "**/spec/**/*"
