language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
services:
  - docker
before_install:
  - mkdir -p /tmp/ftp
  - docker run -d -p 7021:21 -p 21000-21010:21000-21010 -e USERS="ftpuser|ftppass" delfer/alpine-ftp-server
  - docker run -d -p 7022:22 sickp/alpine-sshd:7.5-r2
  - gem install bundler
cache: bundler
